services:
  - type: web
    name: moon-chess-relay
    env: python
    region: singapore
    buildCommand: pip install -r moon_chess/requirements-relay.txt
    startCommand: python moon_chess/src/relay_server.py
    plan: free
# ignore
